Nozama/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using Nozama.DAL;
using Nozama.Models;

namespace Nozama.Controllers
{
    public class StoreController : Controller
    {
        private NozamaContext db = new NozamaContext();

        // GET: Store
        //public ActionResult Index()
        //{
        //    return View();
        //}


        public ActionResult Index(string productType, string productDesc)
        {

            var products = from p in db.Products
                         select p;

            if (!string.IsNullOrEmpty(productType))
            {
                products = products.Where(s => s.ProductType.ToString().Contains(productType));

            }

            if (!string.IsNullOrEmpty(productDesc))
            {
                products = products.Where(s => s.Description.Contains(productDesc));
            }

            return View(products);
            
        }

        // GET: Store/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductType,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Store/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Store/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductType,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Store/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Store/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Store/AddCart/5
        public ActionResult AddCart(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            Guid sessionId;
            var cookie = Request.Cookies["session"];
            if (cookie == null || !System.Guid.TryParse(cookie.Value, out sessionId))
            {
                sessionId = System.Guid.NewGuid();
                Response.Cookies.Add(new HttpCookie("session", sessionId.ToString()));
            }
            else
            {
                sessionId = new Guid(cookie.Value);
            }

            Response.Cookies.Add(new HttpCookie("session", sessionId.ToString()));

            var cart = db.Carts.Find(sessionId);
            if (cart == null)
            {
                var products = new List<Product> {product};
                db.Carts.Add(
                    new Cart()
                    {
                        CartId = sessionId,
                    }
                );
                db.SaveChanges();
            }

            db.CartProducts.Add(new CartProducts()
            {
                CartProductId = System.Guid.NewGuid(),
                Cart = db.Carts.Find(sessionId),
                Product = product
            });
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nozama/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nozama</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nozama", "Index", "Store", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Store")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>

                    <li>@Html.ActionLink("Cart", "Index", "Cart")</li>
                    <li>@Html.ActionLink("Checkout", "Index", "Checkout")</li>
                    <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Nozama, Inc.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>